name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 10
        uses: actions/setup-java@v1
        with:
          java-version: 10
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Dev Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: phantom
          path: /home/runner/work/phantom/phantom/target/phantom*.jar
